from django.db import models


class SeedUtterance(models.Model):
    '''holds the original utterance that we seek to generate alternatives for.
    '''
    def __str__(self):
        return self.seed_text

    seed_text = models.CharField(max_length=200)


class GeneratedUtterances(models.Model):
    '''holds utterances generated by UtteranceGenerator from /utils.
    '''
    def __str__(self):
        return self.generated_text

    seed_utterance = models.ForeignKey(SeedUtterance, on_delete=models.CASCADE)
    generated_text = models.CharField(max_length=200)

