from django.db import models


class Utterance(models.Model):
    '''holds the original utterance that we seek to generate alternatives for.
    '''
    def __str__(self):
        return self.utterance_text

    utterance_text = models.CharField(max_length=200)


class GeneratedUtterances(models.Model):
    '''holds utterances generated by UtteranceGenerator from /utils.
    '''
    def __str__(self):
        return self.generated

    seed                 = models.ForeignKey(Utterance, on_delete=models.CASCADE)
    generated_utterance  = models.CharField(max_length=200)
    keep                 = models.BooleanField(default=False)
