# Generated by Django 4.0.5 on 2022-07-01 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utterance_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedUtterances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated', models.CharField(max_length=200)),
                ('utterance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.utterance')),
            ],
        ),
    ]
