# Generated by Django 4.0.5 on 2022-07-07 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeedUtterance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedUtterance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_text', models.CharField(max_length=200)),
                ('to_be_exported', models.BooleanField(default=False)),
                ('seed_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.seedutterance')),
            ],
        ),
    ]
