# Generated by Django 4.0.5 on 2022-07-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedutterances',
            old_name='generated',
            new_name='generated_utterance',
        ),
        migrations.RenameField(
            model_name='generatedutterances',
            old_name='utterance',
            new_name='seed',
        ),
        migrations.AddField(
            model_name='generatedutterances',
            name='keep',
            field=models.BooleanField(default=False),
        ),
    ]
