# Generated by Django 4.0.5 on 2022-07-08 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_rename_generatedutterance_generatedutterances_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedutterances',
            name='to_be_exported',
        ),
    ]
